name: Bánh Mì
favicon: null
layout_spectrum: 0.27346
typography_spectrum: 0.25903
title: Vietnamese street food
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#614225'
    - '#c5b9ae'
    - '#a08e7c'
    - '#79a0d1'
  brandStrength: 0.8125
  lightness: 0.7711962449830025
  saturation: 0.054474371019750834
  rhythmicContrast: 0.6161818066611886
purpose: []
